# Generated by Django 3.1.3 on 2021-10-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestorVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.PositiveIntegerField(default=18)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Bloqueado', 'Bloqueado')], max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestorVentas.rol')),
            ],
        ),
    ]
