# Generated by Django 3.1.3 on 2021-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('ID_Rol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('ID_Rol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
